# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa62ce8bf4432b129c7fb0d48e25cccfeb3809dd4e16d248fcef5ff1b57a392aeb053ea3bb417bf539725bd6b9c537a93d4e5022d7466650831981f1011eb89e

test:
  secret_key_base: bdb2372a262a8932a789ae5d02fdc8d663d6964998744d156598d1fee1e4c9a715520d22e388a66211214f155a03dc2cdecfabded11ff56a6a44dcd059a264a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
